# Generated by Django 4.2.7 on 2024-04-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.CharField(default='Student', editable=False, max_length=10),
        ),
    ]
