# Generated by Django 4.2.7 on 2024-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default='teachers/images/default.jpg', null=True, upload_to='teachers/images/'),
        ),
    ]
