# Generated by Django 4.2.7 on 2024-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_type',
            field=models.CharField(default='Teacher', editable=False, max_length=10),
        ),
    ]
