# Generated by Django 4.2.7 on 2024-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_credit_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
