# Generated by Django 4.2.7 on 2024-03-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('courses', '0005_course_department_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department_slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
