# Generated by Django 4.2.7 on 2024-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_enrollment',
            field=models.IntegerField(default=0),
        ),
    ]
