# Generated by Django 4.2.7 on 2024-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user_type'),
        ('courses', '0008_course_total_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
