# Generated by Django 5.2.17 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("icon", models.CharField(blank=True, max_length=8)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
